language: objective-c 
osx_image: xcode7.2
xcode_workspace: MapTheFuture/Wanderful.xcworkspace 
xcode_scheme: MapTheFuture
podfile: MapTheFuture/Podfile


script:

  xctool
  -workspace MapTheFuture/Wanderful.xcworkspace 
  -scheme MapTheFuture
  -sdk iphonesimulator
  -destination 'platform=iOS Simulator,name=iPhone 6s'
  build 
  test
  ONLY_ACTIVE_ARCH=NO
  CODE_SIGN_IDENTITY=""
  CODE_SIGNING_REQUIRED=NO

before_install:
  - brew update
  - brew uninstall xctool && brew install --HEAD xctool