# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'MapTheFuture' do

pod 'IQAudioRecorderController'
pod 'Alamofire', '~> 3.0'
pod 'AlamofireObjectMapper', '~> 2.1'

end

target 'MapTheFutureTests' do

end

